#!/bin/bash
set -euo pipefail

export LOG_FILE="${LOG_FILE:-/mnt/shared-storage-user/puyuan/code/OpenClaw-RL/tmp_doc_latest/docker_watchdog.log}"
export POOL_HOST="${POOL_HOST:-127.0.0.1}"
export POOL_PORT="${POOL_PORT:-18081}"
export POOL_CHECK_INTERVAL="${POOL_CHECK_INTERVAL:-30}"
export POOL_PENDING_CLOSES_WARN="${POOL_PENDING_CLOSES_WARN:-50}"
export POOL_PENDING_CLOSES_REPAIR="${POOL_PENDING_CLOSES_REPAIR:-1}"
export POOL_PENDING_CLOSES_REPAIR_THRESHOLD="${POOL_PENDING_CLOSES_REPAIR_THRESHOLD:-50}"
export POOL_PENDING_CLOSES_STUCK_CHECKS="${POOL_PENDING_CLOSES_STUCK_CHECKS:-3}"
export POOL_PENDING_CLOSES_ACTIVE_MAX="${POOL_PENDING_CLOSES_ACTIVE_MAX:-64}"
export POOL_PENDING_CLOSES_REAP_LIMIT="${POOL_PENDING_CLOSES_REAP_LIMIT:-0}"
export POOL_PENDING_CLOSES_REPAIR_COOLDOWN_S="${POOL_PENDING_CLOSES_REPAIR_COOLDOWN_S:-300}"
export POOL_PENDING_CLOSES_CANCEL_API="${POOL_PENDING_CLOSES_CANCEL_API:-1}"
export POOL_PENDING_CLOSES_CANCEL_TIMEOUT="${POOL_PENDING_CLOSES_CANCEL_TIMEOUT:-5}"
export POOL_PENDING_CLOSES_CANCEL_MIN_AGE="${POOL_PENDING_CLOSES_CANCEL_MIN_AGE:-90}"
export MAX_RUNNING_CONTAINERS="${MAX_RUNNING_CONTAINERS:-96}"
export HARD_KILL_THRESHOLD="${HARD_KILL_THRESHOLD:-160}"
export TASK_CONTAINER_REGEX='^[0-9]+[-_].*(slime[-_]?run|client|helper).*$'
export TASK_IMAGE_REGEX='^tb__[0-9]+__.*(:|$)'
export WATCHDOG_AGGRESSIVE_IMAGE_PRUNE="${WATCHDOG_AGGRESSIVE_IMAGE_PRUNE:-0}"

cd /mnt/shared-storage-user/puyuan/code/OpenClaw-RL
exec bash terminal-rl/remote/docker_watchdog_v2.sh
