#!/usr/bin/env bash
# Default SETA-only robust exploration launch for Qwen3-8B.
#
# This wrapper pins the dataset to SETA and enables the robust exploration
# defaults discussed in the reward review. It delegates execution to
# terminal-rl_qwen3-8b_exploration_pu.sh so runtime_env propagation and the
# training command stay centralized.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%Y-%m-%d_%H%M%S)}"
NUM_GPUS="${NUM_GPUS:-8}"

DATASET="${DATASET:-seta}"
ALGO="${ALGO:-dapo}"
HARNESS_OPTION="${HARNESS_OPTION:-camel-agent}"

# Keep the default run name explicit enough for later ablations.
RUN_ID="${RUN_ID:-terminal-rl_qwen3-8b_${NUM_GPUS}gpu_seta_dapo_exploration_epi_mean_life_label_decay0.995_ngu_dualadv_think_${RUN_TIMESTAMP}}"
RUN_NAME="${RUN_NAME:-${RUN_ID}}"

# Rollout / training size defaults from the mixed robust exploration run.
ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-4}"
N_SAMPLES="${N_SAMPLES:-8}"
MAX_TURN="${MAX_TURN:-10}"
MAX_CKPT_KEEP="${MAX_CKPT_KEEP:-2}"
TRAJECTORY_SAVE_INTERVAL="${TRAJECTORY_SAVE_INTERVAL:-10}"
EXTRA_DAPO_ARGS="${EXTRA_DAPO_ARGS:---dynamic-sampling-max-groups 64 --dynamic-sampling-max-seconds 1800 --rollout-abort-wait-timeout 300}"
ROUTER_READY_WAIT_FOREVER="${ROUTER_READY_WAIT_FOREVER:-1}"
AUTO_CLOSE_STALE_WORKER_RUNS="${AUTO_CLOSE_STALE_WORKER_RUNS:-1}"
STALE_WORKER_CLOSE_INTERVAL="${STALE_WORKER_CLOSE_INTERVAL:-10}"
STALE_WORKER_CLOSE_TIMEOUT="${STALE_WORKER_CLOSE_TIMEOUT:-10}"
STALE_WORKER_REPAIR_MIN_AGE="${STALE_WORKER_REPAIR_MIN_AGE:-0}"
STALE_WORKER_REPAIR_MAX_REPAIRS="${STALE_WORKER_REPAIR_MAX_REPAIRS:-20}"

# SETA reward defaults.
SETA_SAFETY="${SETA_SAFETY:-none}"
SAFETY_REWARD_COEF="${SAFETY_REWARD_COEF:-0}"

# Robust exploration defaults.
CUSTOM_CONFIG_PATH="${CUSTOM_CONFIG_PATH:-${SCRIPT_DIR}/configs/rollout_qwen3_think.yaml}"
EXPLORATION_PROFILE="${EXPLORATION_PROFILE:-spear_lite}"
EXPLORE_THINK_MODE="${EXPLORE_THINK_MODE:-1}"
EXPLORE_INTRINSIC="${EXPLORE_INTRINSIC:-1}"
EXPLORE_INTRINSIC_COEF="${EXPLORE_INTRINSIC_COEF:-0.015}"
EXPLORE_INTRINSIC_SCHEDULE="${EXPLORE_INTRINSIC_SCHEDULE:-cosine}"
EXPLORE_INTRINSIC_DECAY_STEPS="${EXPLORE_INTRINSIC_DECAY_STEPS:-120}"
EXPLORE_INTRINSIC_REDUCER="${EXPLORE_INTRINSIC_REDUCER:-mean}"
EXPLORE_INTRINSIC_GRANULARITY="${EXPLORE_INTRINSIC_GRANULARITY:-signature}"
EXPLORE_INTRINSIC_SCOPE="${EXPLORE_INTRINSIC_SCOPE:-episode}"
EXPLORE_SCORE_BONUS_COMPONENTS="${EXPLORE_SCORE_BONUS_COMPONENTS:-none}"

EXPLORE_AGENT57_LITE="${EXPLORE_AGENT57_LITE:-1}"
EXPLORE_AGENT57_K="${EXPLORE_AGENT57_K:-8}"
EXPLORE_AGENT57_ARM_BETAS="${EXPLORE_AGENT57_ARM_BETAS:-0,0.002,0.004,0.006,0.008,0.01,0.015,0.02}"
EXPLORE_AGENT57_COMBINE_MODE="${EXPLORE_AGENT57_COMBINE_MODE:-ngu_lite}"
EXPLORE_AGENT57_NGU_EPISODIC_SOURCE="${EXPLORE_AGENT57_NGU_EPISODIC_SOURCE:-signature_intrinsic}"
EXPLORE_AGENT57_NGU_EPISODIC_REDUCER="${EXPLORE_AGENT57_NGU_EPISODIC_REDUCER:-${EXPLORE_INTRINSIC_REDUCER}}"
EXPLORE_AGENT57_NGU_LIFE_MOD_MODE="${EXPLORE_AGENT57_NGU_LIFE_MOD_MODE:-standardized_softplus}"
EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP="${EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP:-5.0}"
EXPLORE_AGENT57_NGU_MOD_CLIP="${EXPLORE_AGENT57_NGU_MOD_CLIP:-5.0}"
EXPLORE_AGENT57_MAX_BONUS="${EXPLORE_AGENT57_MAX_BONUS:-0.05}"
EXPLORE_AGENT57_CONTROLLER="${EXPLORE_AGENT57_CONTROLLER:-fixed}"
EXPLORE_AGENT57_UCB_RANDOM_SEED="${EXPLORE_AGENT57_UCB_RANDOM_SEED:-20260605}"

EXPLORE_AGENT57_LIFELONG="${EXPLORE_AGENT57_LIFELONG:-1}"
EXPLORE_AGENT57_LIFELONG_BACKEND="${EXPLORE_AGENT57_LIFELONG_BACKEND:-sqlite}"
EXPLORE_AGENT57_LIFELONG_COEF="${EXPLORE_AGENT57_LIFELONG_COEF:-0.005}"
EXPLORE_AGENT57_LIFELONG_CLIP="${EXPLORE_AGENT57_LIFELONG_CLIP:-2.0}"
EXPLORE_AGENT57_LIFELONG_WARMUP="${EXPLORE_AGENT57_LIFELONG_WARMUP:-64}"
EXPLORE_AGENT57_LIFELONG_COUNT_DECAY="${EXPLORE_AGENT57_LIFELONG_COUNT_DECAY:-0.995}"
EXPLORE_AGENT57_LIFELONG_CAPACITY="${EXPLORE_AGENT57_LIFELONG_CAPACITY:-200000}"
EXPLORE_AGENT57_LIFELONG_KEY_VERSION="${EXPLORE_AGENT57_LIFELONG_KEY_VERSION:-v2}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET="${EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET:-1}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK="${EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK:-0}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN="${EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN:-0}"
EXPLORE_AGENT57_LIFELONG_OBS_MODE="${EXPLORE_AGENT57_LIFELONG_OBS_MODE:-label}"

EXPLORE_AGENT57_TRUST_GATE="${EXPLORE_AGENT57_TRUST_GATE:-soft}"
EXPLORE_AGENT57_TRUST_COMPLETED="${EXPLORE_AGENT57_TRUST_COMPLETED:-1.0}"
EXPLORE_AGENT57_TRUST_TRUNCATED="${EXPLORE_AGENT57_TRUST_TRUNCATED:-0.3}"
EXPLORE_AGENT57_TRUST_FAILED="${EXPLORE_AGENT57_TRUST_FAILED:-0.1}"
EXPLORE_AGENT57_TRUST_PARSE_ERROR="${EXPLORE_AGENT57_TRUST_PARSE_ERROR:-0.1}"
EXPLORE_AGENT57_TRUST_WARMUP="${EXPLORE_AGENT57_TRUST_WARMUP:-0.3}"

EXPLORE_ADVANTAGE_BONUS="${EXPLORE_ADVANTAGE_BONUS:-1}"
EXPLORE_ADVANTAGE_BONUS_MODE="${EXPLORE_ADVANTAGE_BONUS_MODE:-dual_stream}"
EXPLORE_ADVANTAGE_INTRINSIC_KEY="${EXPLORE_ADVANTAGE_INTRINSIC_KEY:-explore_agent57_intrinsic_signal}"
EXPLORE_ADVANTAGE_LAMBDA="${EXPLORE_ADVANTAGE_LAMBDA:-0.1}"
EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE="${EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE:-normalized_beta}"
EXPLORE_ADVANTAGE_TRUST_KEY="${EXPLORE_ADVANTAGE_TRUST_KEY:-explore_agent57_trust}"
EXPLORE_ADVANTAGE_BONUS_CLIP="${EXPLORE_ADVANTAGE_BONUS_CLIP:-0}"

# Keep overlapping curiosity terms opt-in for clean ablation.
EXPLORE_CDE_ACTOR="${EXPLORE_CDE_ACTOR:-0}"
EXPLORE_LPRND="${EXPLORE_LPRND:-0}"
EXPLORE_SAFETY_FILTER="${EXPLORE_SAFETY_FILTER:-0}"

export RUN_TIMESTAMP NUM_GPUS RUN_ID RUN_NAME
export DATASET ALGO HARNESS_OPTION
export ROLLOUT_BATCH_SIZE N_SAMPLES MAX_TURN MAX_CKPT_KEEP TRAJECTORY_SAVE_INTERVAL EXTRA_DAPO_ARGS
export ROUTER_READY_WAIT_FOREVER AUTO_CLOSE_STALE_WORKER_RUNS STALE_WORKER_CLOSE_INTERVAL STALE_WORKER_CLOSE_TIMEOUT
export STALE_WORKER_REPAIR_MIN_AGE STALE_WORKER_REPAIR_MAX_REPAIRS
export SETA_SAFETY SAFETY_REWARD_COEF CUSTOM_CONFIG_PATH
export EXPLORATION_PROFILE EXPLORE_THINK_MODE
export EXPLORE_INTRINSIC EXPLORE_INTRINSIC_COEF EXPLORE_INTRINSIC_SCHEDULE EXPLORE_INTRINSIC_DECAY_STEPS
export EXPLORE_INTRINSIC_REDUCER EXPLORE_INTRINSIC_GRANULARITY EXPLORE_INTRINSIC_SCOPE EXPLORE_SCORE_BONUS_COMPONENTS
export EXPLORE_AGENT57_LITE EXPLORE_AGENT57_K EXPLORE_AGENT57_ARM_BETAS EXPLORE_AGENT57_COMBINE_MODE
export EXPLORE_AGENT57_NGU_EPISODIC_SOURCE EXPLORE_AGENT57_NGU_EPISODIC_REDUCER
export EXPLORE_AGENT57_NGU_LIFE_MOD_MODE EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP
export EXPLORE_AGENT57_NGU_MOD_CLIP EXPLORE_AGENT57_MAX_BONUS EXPLORE_AGENT57_CONTROLLER EXPLORE_AGENT57_UCB_RANDOM_SEED
export EXPLORE_AGENT57_LIFELONG EXPLORE_AGENT57_LIFELONG_BACKEND EXPLORE_AGENT57_LIFELONG_COEF
export EXPLORE_AGENT57_LIFELONG_CLIP EXPLORE_AGENT57_LIFELONG_WARMUP
export EXPLORE_AGENT57_LIFELONG_COUNT_DECAY EXPLORE_AGENT57_LIFELONG_CAPACITY
export EXPLORE_AGENT57_LIFELONG_KEY_VERSION EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET
export EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN EXPLORE_AGENT57_LIFELONG_OBS_MODE
export EXPLORE_AGENT57_TRUST_GATE EXPLORE_AGENT57_TRUST_COMPLETED EXPLORE_AGENT57_TRUST_TRUNCATED
export EXPLORE_AGENT57_TRUST_FAILED EXPLORE_AGENT57_TRUST_PARSE_ERROR EXPLORE_AGENT57_TRUST_WARMUP
export EXPLORE_ADVANTAGE_BONUS EXPLORE_ADVANTAGE_BONUS_MODE EXPLORE_ADVANTAGE_INTRINSIC_KEY
export EXPLORE_ADVANTAGE_LAMBDA EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE EXPLORE_ADVANTAGE_TRUST_KEY EXPLORE_ADVANTAGE_BONUS_CLIP
export EXPLORE_CDE_ACTOR EXPLORE_LPRND EXPLORE_SAFETY_FILTER

exec bash "${SCRIPT_DIR}/terminal-rl_qwen3-8b_exploration_pu.sh" "$@"
